{{- if .Values.app.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "chart.fullname" . }}-app"
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
    - port: 35729
      targetPort: 35729
      protocol: TCP
      name: hot-reloading
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    aragon.org/court-backend-application: app
{{- end -}}