{
 "title": "Protocol Backend",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "label_values({job=~\"(.*/)?protocol-backend(-.*)?\"}, service)"
   }
  ]
 },
 "panels": [
  { "title": "Server and Services up status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (service) (up{service=\"$service\",endpoint=\"server-metrics\"})"
    }
   ]
  },
  {
   "title": "Heartbeat",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (service) (up{service=\"$service\",endpoint=\"metrics-hbeat\"})"
    }
   ]
  },
  {
   "title": "Reveal",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (service) (up{service=\"$service\",endpoint=\"metrics-reveal\"})"
    }
   ]
  },
  {
   "title": "Settlements",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (service) (up{service=\"$service\",endpoint=\"metrics-settle\"})"
    }
   ]
  },
  {
   "title": "Monitor Keeper",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (service) (up{service=\"$service\",endpoint=\"metrics-keeper\"})"
    }
   ]
  },
  {
   "title": "Notification Scanner",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (service) (up{service=\"$service\",endpoint=\"metrics-scanner\"})"
    }
   ]
  },
  {
   "title": "Notification Sender",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (service) (up{service=\"$service\",endpoint=\"metrics-sender\"})"
    }
   ]
  },
  { "title": "Failing transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "reveal",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (service) (transaction_errors{service=\"$service\",type=\"reveal\"})"
    }
   ]
  },
  {
   "title": "settleReward",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (service) (transaction_errors{service=\"$service\",type=\"settleReward\"})"
    }
   ]
  },
  {
   "title": "settlePenalties",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (service) (transaction_errors{service=\"$service\",type=\"settlePenalties\"})"
    }
   ]
  },
  {
   "title": "executeRuling",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (service) (transaction_errors{service=\"$service\",type=\"executeRuling\"})"
    }
   ]
  },
  {
   "title": "heartbeat",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (service) (transaction_errors{service=\"$service\",type=\"heartbeat\"})"
    }
   ]
  },
  { "title": "Server Metrics and Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Server status codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code) (rate(http_requests_total{service=\"$service\"}[5m]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Server 4** by path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (irate(http_requests_total{service=\"$service\",status_code=~\"4.*\"}[5m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Server logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{app=\"$service\",container=~\".*server.*\"}"
    }
   ]
  },
  {
   "title": "Server 5** by path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (irate(http_requests_total{service=\"$service\",status_code=~\"5.*\"}[5m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "Services Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Service worker successful runs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (workerName) (rate(worker_success{service=\"$service\"}[30m]))",
     "legendFormat": "{{workerName}}"
    }
   ]
  },
  {
   "title": "Notification scan runs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (scannerName) (rate(notifications_scanned{service=\"$service\"}[30m]))",
     "legendFormat": "{{scannerName}}"
    }
   ]
  },
  {
   "title": "Service worker errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (workerName) (irate(worker_errors{service=\"$service\"}[5m]))",
     "legendFormat": "{{workerName}}"
    }
   ]
  },
  {
   "title": "Notification emails sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (scannerName) (rate(notifications_sent{service=\"$service\"}[30m]))",
     "legendFormat": "{{scannerName}}"
    }
   ]
  },
  { "title": "Services Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Heartbeats",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "{app=\"$service\",container=~\".*services.*\"}|=\"[heartbeat]\""
    }
   ]
  },
  {
   "title": "Reveals",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "{app=\"$service\",container=~\".*services.*\"}|=\"[reveal]\""
    }
   ]
  },
  {
   "title": "Settlements",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "{app=\"$service\",container=~\".*services.*\"}|=\"[settlements]\""
    }
   ]
  },
  {
   "title": "Monitor keeper",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "{app=\"$service\",container=~\".*services.*\"}|=\"[monitor-keeper]\""
    }
   ]
  },
  {
   "title": "Notification scanner",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "{app=\"$service\",container=~\".*services.*\"}|=\"[notification-scanner]\""
    }
   ]
  },
  {
   "title": "Notification sender",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "{app=\"$service\",container=~\".*services.*\"}|=\"[notification-sender]\""
    }
   ]
  },
  {
   "title": "RPC calls",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "{app=\"$service\",container=~\".*services.*\"}|=\"[Provider]\""
    }
   ]
  },
  {
   "title": "All service logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "{app=\"$service\",container=~\".*services.*\"}"
    }
   ]
  },
  { "title": "Backoffice logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Backoffice logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "{app=\"$service\",container=~\".*(app|backoffice).*\"}"
    }
   ]
  }
 ]
}