{{- if .Values.server.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "chart.fullname" . }}-server"
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.server.autoscaling.enabled }}
  replicas: {{ .Values.server.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
        aragon.org/court-backend-application: server
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: "app"
              containerPort: 8000
            - name: "hot-reloading"
              containerPort: 35729
          env:
            - name: SERVER_PORT
              value: "8000"
            - name: SERVER_METRICS_PORT
              value: "9091"
            - name: SERVICE_PORT_HEARTBEAT
              value: "9081"
            - name: SERVICE_PORT_REVEAL
              value: "9082"
            - name: SERVICE_PORT_SETTLEMENTS
              value: "9083"
            - name: SERVICE_PORT_MONITOR_KEEPER
              value: "9084"
            - name: SERVICE_PORT_NOTIFICATION_SCANNER
              value: "9085"
            - name: SERVICE_PORT_NOTIFICATION_SENDER
              value: "9086"
            - name: SERVICE_PORT_CONTRACT_MONITOR
              value: "9087"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ template "chart.serverSecretName" . }}
                  key: dbName
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ template "chart.serverSecretName" . }}
                  key: dbHost
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ template "chart.serverSecretName" . }}
                  key: dbPort
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "chart.serverSecretName" . }}
                  key: dbUser
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ template "chart.serverSecretName" . }}
                  key: dbPass
            - name: CORS_WHITELIST
              valueFrom:
                configMapKeyRef:
                  name: {{ template "chart.serverConfigName" . }}
                  key: corsWhitelist
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "chart.serverSecretName" . }}
                  key: sessionSecret
            - name: SESSION_SECURE
              valueFrom:
                secretKeyRef:
                  name: {{ template "chart.serverSecretName" . }}
                  key: sessionSecure
            - name: ETHERSCAN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "chart.serverSecretName" . }}
                  key: etherscanApiKey
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "chart.serverSecretName" . }}
                  key: privateKey
            - name: NETWORK
              valueFrom:
                configMapKeyRef:
                  name: {{ template "chart.serverConfigName" . }}
                  key: network
            - name: COURT_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: {{ template "chart.serverSecretName" . }}
                  key: courtAddress
            - name: RPC
              valueFrom:
                configMapKeyRef:
                  name: {{ template "chart.serverConfigName" . }}
                  key: rpc
            - name: GAS
              valueFrom:
                configMapKeyRef:
                  name: {{ template "chart.serverConfigName" . }}
                  key: gas
            - name: GAS_PRICE
              valueFrom:
                configMapKeyRef:
                  name: {{ template "chart.serverConfigName" . }}
                  key: gasPrice
            - name: WEB3_POLLING_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: {{ template "chart.serverConfigName" . }}
                  key: web3PollingInterval
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ template "chart.serverSecretName" . }}
                  key: adminEmail
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "chart.serverSecretName" . }}
                  key: adminPass
            - name: EMAIL_JWT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "chart.serverSecretName" . }}
                  key: emailJwtPrivate
            - name: POSTMARK_SERVER_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "chart.serverSecretName" . }}
                  key: postmarkApiToken
            - name: EMAIL_FROM_DEFAULT
              valueFrom:
                configMapKeyRef:
                  name: {{ template "chart.serverConfigName" . }}
                  key: emailFromDefault
            - name: POSTMARK_TEMPLATE_ALIAS_VERIFY
              valueFrom:
                configMapKeyRef:
                  name: {{ template "chart.serverConfigName" . }}
                  key: postmarkTemplateAliasVerify
          args:
            - "npm"
            - "run"
            - "start:server"
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}