{{- if and (not .Values.server.secret.existingSecret) .Values.server.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "chart.fullname" . }}-server-secret"
type: Opaque
data:
  dbName: {{ .Values.server.secret.dbName | default "" | quote | b64enc }}
  dbHost: {{ .Values.server.secret.dbHost | default "" | quote | b64enc }}
  dbPort: {{ .Values.server.secret.dbPort | default "" | quote | b64enc }}
  dbUser: {{ .Values.server.secret.dbUser | default "" | quote | b64enc }}
  dbPass: {{ .Values.server.secret.dbPass | default "" | quote | b64enc }}
  adminEmail: {{ .Values.server.secret.adminEmail | default "" | quote | b64enc }}
  adminPass: {{ .Values.server.secret.adminPass | default "" | quote | b64enc }}
  etherscanApiKey: {{ .Values.server.secret.etherscanApiKey | default "" | quote | b64enc }}
  privateKey: {{ .Values.server.secret.privateKey | default "" | quote | b64enc }}
  courtAddress: {{ .Values.server.secret.courtAddress | default "" | quote | b64enc }}
  emailJwtPrivate: {{ .Values.server.secret.emailJwtPrivate | default "" | quote | b64enc }}
  postmarkApiToken: {{ .Values.server.secret.postmarkApiToken | default "" | quote | b64enc }}
  sessionSecret: {{ .Values.server.secret.sessionSecret | default "" | quote | b64enc }}
  sessionSecure: {{ .Values.server.secret.sessionSecure | default "" | quote | b64enc }}
{{- end -}}