# This config is required for Prometheus to scrape other containers
scrape_configs:
- job_name: protocol-backend
  static_configs:
  - targets: 
    - server:9091
    labels:
      service: protocol-backend
      endpoint: server-metrics
  - targets: 
    - services:9081
    labels:
      service: protocol-backend
      endpoint: metrics-hbeat
  - targets: 
    - services:9082
    labels:
      service: protocol-backend
      endpoint: metrics-reveal
  - targets: 
    - services:9083
    labels:
      service: protocol-backend
      endpoint: metrics-settle
  - targets: 
    - services:9084
    labels:
      service: protocol-backend
      endpoint: metrics-keeper
  - targets: 
    - services:9085
    labels:
      service: protocol-backend
      endpoint: metrics-scanner
  - targets: 
    - services:9086
    labels:
      service: protocol-backend
      endpoint: metrics-sender
  - targets: 
    - services:9087
    labels:
      service: protocol-backend
      endpoint: metrics-monitor
