{{- if and .Values.service.autoscaling.enabled .Values.service.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ include "chart.fullname" . }}-service"
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ include "chart.fullname" . }}-service"
  minReplicas: {{ .Values.service.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.service.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.service.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.service.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.service.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.service.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
