{{- if and (not .Values.service.secret.existingSecret) .Values.service.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "chart.fullname" . }}-service-secret"
type: Opaque
data:
  postmarkApiToken: {{ .Values.service.secret.postmarkApiToken | default "" | quote | b64enc }}
  etherscanApiKey: {{ .Values.service.secret.etherscanApiKey | default "" | quote | b64enc }}
  privateKey: {{ .Values.service.secret.privateKey | default "" | quote | b64enc }}
{{- end -}}