name: Mainnet CI/CD
on:
  push:
    tags:
    - v*
env:
  # This is a base repository and we use ${GITHUB_REF##*/} to set the version of the container
  REPO: aragon/protocol-backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker login -u ${{secrets.DOCKERHUB_USER}} -p ${{secrets.DOCKERHUB_TOKEN}}
    - run: .github/scripts/docker-build.sh $REPO ${GITHUB_SHA}

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - run: docker login -u ${{secrets.DOCKERHUB_USER}} -p ${{secrets.DOCKERHUB_TOKEN}}
    - run: .github/scripts/test/run.sh $REPO:${GITHUB_SHA}

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - run: docker login -u ${{secrets.DOCKERHUB_USER}} -p ${{secrets.DOCKERHUB_TOKEN}}
    - run: .github/scripts/docker-release.sh $REPO:${GITHUB_SHA} $REPO:${GITHUB_REF##*/}
    - run: .github/scripts/docker-release.sh $REPO:${GITHUB_SHA} $REPO:latest

  deploy:
    runs-on: ubuntu-latest
    needs: release
    steps:
    - uses: actions/checkout@v2
    - run: .github/scripts/kubectl-config.sh ${{secrets.KUBE_CA}} ${{secrets.KUBE_SERVER}} ${{secrets.KUBE_TOKEN}}
    - run: .github/scripts/kubectl-set-image.sh protocol-backend $REPO:${GITHUB_REF##*/}
    - run: .github/scripts/kubectl-wait-ready.sh protocol-backend
    # wait 10 sec for k8s to reroute ingress and check app endpoint
    - run: sleep 10 && curl --fail https://protocol-app.backend.aragon.org
